#!/usr/bin/csh -f


#ENV setting
setenv PROJ_NAME prj_test
setenv KPP_TYPE build_variant
setenv TESTCONFIG /proj/abcd/test.config
setenv PROJECT    /hoangbn/prj_test
setenv RTL_ROOT   /hoangbn/rtl
setenv RTL_ROOT   /hoangbn/rtl
